"""initial migration

Revision ID: 16785b651d95
Revises: 
Create Date: 2019-03-17 18:56:57.175182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16785b651d95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performerdetailtable')
    op.drop_table('movietable')
    op.drop_table('movieperformertable')
    op.drop_table('movieurl')
    op.drop_table('categroymovietable')
    op.drop_table('moviedetailtable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moviedetailtable',
    sa.Column('id', mysql.INTEGER(display_width=100), autoincrement=False, nullable=True),
    sa.Column('director', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('keyword', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('categroy', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('des', mysql.VARCHAR(length=3000), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('categroymovietable',
    sa.Column('numid', mysql.INTEGER(display_width=100), autoincrement=True, nullable=False),
    sa.Column('categroy', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('numid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('movieurl',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('movieurl', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('movieperformertable',
    sa.Column('id', mysql.INTEGER(display_width=100), autoincrement=False, nullable=True),
    sa.Column('performer', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('movietable',
    sa.Column('id', mysql.INTEGER(display_width=100), autoincrement=True, nullable=False, comment='?????'),
    sa.Column('moviename', mysql.VARCHAR(length=100), nullable=True, comment='????'),
    sa.Column('time', mysql.VARCHAR(length=100), nullable=True, comment='??????'),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=True, comment='????'),
    sa.Column('imagepath', mysql.VARCHAR(length=2000), nullable=True, comment='????'),
    sa.Column('saveimagepath', mysql.VARCHAR(length=500), nullable=True, comment='????????'),
    sa.Column('score', mysql.FLOAT(precision=10, scale=1), nullable=True, comment='??'),
    sa.Column('status', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True, comment='????'),
    sa.Column('source', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('performerdetailtable',
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('e_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('alias', mysql.VARCHAR(length=200), nullable=True, comment='??'),
    sa.Column('sex', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=True),
    sa.Column('bloodtype', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('height', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('birthday', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('constellation', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ResidentialAddress', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('school', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('BrokerageAgency', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('fameyear', mysql.VARCHAR(length=200), nullable=True, comment='????'),
    sa.Column('hobby', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('Occupation', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('weight', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('des', mysql.VARCHAR(length=2000), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
