"""v1

Revision ID: b8b4c6131bb3
Revises: 
Create Date: 2019-04-14 11:33:39.423372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8b4c6131bb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SourceTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MYGROUPID', sa.String(length=100), nullable=True),
    sa.Column('NETURL', sa.String(length=200), nullable=True),
    sa.Column('PHOTOSAVEPATH', sa.String(length=100), nullable=True),
    sa.Column('PICTUREDES', sa.String(length=1000), nullable=True),
    sa.Column('CREATETIME', sa.String(length=100), nullable=True),
    sa.Column('USERID', sa.String(length=100), nullable=True),
    sa.Column('SOURCE', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tagtable',
    sa.Column('NUMID', sa.Integer(), nullable=False),
    sa.Column('CATEGROY', sa.String(length=100), nullable=True),
    sa.Column('TAG', sa.String(length=100), nullable=True),
    sa.Column('TAGDES', sa.String(length=1000), nullable=True),
    sa.Column('TITLE', sa.String(length=1000), nullable=True),
    sa.Column('IMAGEPATH', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('NUMID')
    )
    op.alter_column('movietable', 'source',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movietable', 'source',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.drop_table('tagtable')
    op.drop_table('SourceTable')
    # ### end Alembic commands ###
